/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Beranda;

import Connect.ConnectDB;
import Loginreg.*;
import com.mysql.jdbc.Connection;
import constant.Constants;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class Atur_lembur extends javax.swing.JPanel {

    private Connection conn = (Connection) new ConnectDB().connect();
    private final Dashboard main;

    private String nama;
    private String nik;

    public Atur_lembur(Dashboard main, String nik, String name) {
        initComponents();
        this.main = main;
        this.nama = name;
        this.nik = nik;
        loadData(nik);
        buttonGroup();
//        namaKar.setText(nama);
//        namaKar.setEnabled(false);
        spl.setEnabled(false);
        persetujuan.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spl = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        namaKar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ket = new javax.swing.JTextArea();
        mulai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        selesai = new javax.swing.JTextField();
        tgl = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        nikTxt1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        persetujuan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        s = new javax.swing.JCheckBox();
        td = new javax.swing.JCheckBox();
        r = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        desc = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 253, 246));

        jLabel1.setBackground(new java.awt.Color(30, 30, 30));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Approval Lembur");

        jLabel2.setBackground(new java.awt.Color(30, 30, 30));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("No Spl");

        spl.setBackground(new java.awt.Color(255, 253, 246));
        spl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        spl.setForeground(new java.awt.Color(30, 30, 30));
        spl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spl.setPreferredSize(new java.awt.Dimension(64, 50));
        spl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splActionPerformed(evt);
            }
        });

        Submit.setBackground(new java.awt.Color(0, 0, 102));
        Submit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setText("Submit");
        Submit.setBorderPainted(false);
        Submit.setPreferredSize(new java.awt.Dimension(0, 50));
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(30, 30, 30));
        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 30, 30));
        jLabel4.setText("Tanggal");

        namaKar.setEditable(false);
        namaKar.setBackground(new java.awt.Color(255, 253, 246));
        namaKar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        namaKar.setForeground(new java.awt.Color(30, 30, 30));
        namaKar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        namaKar.setPreferredSize(new java.awt.Dimension(64, 50));
        namaKar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaKarActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(30, 30, 30));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 30, 30));
        jLabel5.setText("Nama Karyawan");

        jLabel6.setBackground(new java.awt.Color(30, 30, 30));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 30, 30));
        jLabel6.setText("Jam Mulai");

        jLabel7.setBackground(new java.awt.Color(30, 30, 30));
        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 30, 30));
        jLabel7.setText("Keterangan");

        ket.setBackground(new java.awt.Color(255, 253, 246));
        ket.setColumns(20);
        ket.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ket.setForeground(new java.awt.Color(30, 30, 30));
        ket.setRows(5);
        ket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(ket);

        mulai.setBackground(new java.awt.Color(255, 253, 246));
        mulai.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        mulai.setForeground(new java.awt.Color(30, 30, 30));
        mulai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mulai.setPreferredSize(new java.awt.Dimension(64, 50));
        mulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(30, 30, 30));
        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(30, 30, 30));
        jLabel8.setText("Jam Selesai");

        selesai.setBackground(new java.awt.Color(255, 253, 246));
        selesai.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        selesai.setForeground(new java.awt.Color(30, 30, 30));
        selesai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        selesai.setPreferredSize(new java.awt.Dimension(64, 50));

        tgl.setBackground(new java.awt.Color(255, 253, 246));
        tgl.setForeground(new java.awt.Color(30, 30, 30));

        tbl.setBackground(new java.awt.Color(255, 253, 246));
        tbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tbl.setForeground(new java.awt.Color(30, 30, 30));
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No Spl", "Nama Karyawan", "Tanggal", "Keterangan"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl);

        jLabel3.setBackground(new java.awt.Color(30, 30, 30));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 30, 30));
        jLabel3.setText("Cari :");

        nikTxt1.setBackground(new java.awt.Color(255, 253, 246));
        nikTxt1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        nikTxt1.setForeground(new java.awt.Color(30, 30, 30));
        nikTxt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nikTxt1.setPreferredSize(new java.awt.Dimension(64, 50));

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cari");
        jButton1.setBorderPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(0, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(30, 30, 30));
        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 30, 30));
        jLabel9.setText("Persetujuan");

        persetujuan.setBackground(new java.awt.Color(255, 253, 246));
        persetujuan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        persetujuan.setForeground(new java.awt.Color(30, 30, 30));
        persetujuan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        persetujuan.setPreferredSize(new java.awt.Dimension(64, 50));

        jLabel10.setBackground(new java.awt.Color(30, 30, 30));
        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(30, 30, 30));
        jLabel10.setText("Status");

        s.setBackground(new java.awt.Color(255, 253, 246));
        s.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        s.setForeground(new java.awt.Color(30, 30, 30));
        s.setText("Disetujui");
        s.setAutoscrolls(true);
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });

        td.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        td.setForeground(new java.awt.Color(30, 30, 30));
        td.setText("Tidak Disetujui");
        td.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdActionPerformed(evt);
            }
        });

        r.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        r.setForeground(new java.awt.Color(30, 30, 30));
        r.setText("Revisi");

        jLabel11.setBackground(new java.awt.Color(30, 30, 30));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(30, 30, 30));
        jLabel11.setText("Keterangan");

        desc.setBackground(new java.awt.Color(255, 253, 246));
        desc.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        desc.setForeground(new java.awt.Color(30, 30, 30));
        desc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        desc.setPreferredSize(new java.awt.Dimension(64, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mulai, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 45, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(s)
                                        .addGap(18, 18, 18)
                                        .addComponent(td)
                                        .addGap(18, 18, 18)
                                        .addComponent(r))
                                    .addComponent(jLabel6))
                                .addGap(0, 387, Short.MAX_VALUE))
                            .addComponent(tgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spl, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(namaKar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(persetujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(nikTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaKar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mulai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(persetujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s)
                    .addComponent(td)
                    .addComponent(r))
                .addGap(10, 10, 10)
                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nikTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addContainerGap(684, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        try {
            String sql = """
                         UPDATE TB_LEMBUR TL
                     
                         SET
                         TL.STATUS_LEMBUR = ?,
                         TL.UPDATE_BY  = ?,
                         TL.UPDATE_AT = ?,
                         TL.APPROVAL_SPV_BY1 = ?,
                         TL.APPROVAL_SPV_ON1 = ?,
                         TL.APPROVAL_SPV_DESC1 = ?
                         WHERE tl.SPL_NO =?
                         """;
            PreparedStatement ps = conn.prepareStatement(sql);

            String select = null;
            java.util.Date utilDate = new java.util.Date();
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

            if (s.isSelected()) {
                select = Constants.SPL_APPROVE;
            }

            if (td.isSelected()) {
                select = Constants.SPL_REJECT;
            }

            if (r.isSelected()) {
                select = Constants.SPL_REVISION;
            }

            ps.setString(1, select);
            ps.setString(2, nik);
            ps.setDate(3, sqlDate);
            ps.setString(4, nik);
            ps.setDate(5, sqlDate);
            ps.setString(6, desc.getText());
            ps.setString(7, spl.getText());
           
            ps.execute();
            loadData(nik);
            
            JOptionPane.showMessageDialog(null, "Data berhasil SUBMIT");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro : " + e.getMessage());
        }
    }//GEN-LAST:event_SubmitActionPerformed
    
    private void loadData(String no) {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("NO SPL");
        model.addColumn("NIK");
        model.addColumn("NAMA KARYAWAN");
        model.addColumn("TANGGAL");
        model.addColumn("JAM MULAI");
        model.addColumn("JAM SELESAI");
        model.addColumn("STATUS");
        model.addColumn("ATASAN");

        try {
            String sql = """
                         SELECT
                                TL.SPL_NO,
                                TK.NIK,
                                TK.NAMA_KARYAWAN,
                                TL.TANGGAL,
                                TL.JAM_MULAI,
                                TL.JAM_SELESAI,
                                TL.STATUS_LEMBUR,
                                TKA.NAMA_KARYAWAN AS NAMA_ATASAN FROM TB_LEMBUR TL 
                                INNER JOIN TB_KARYAWAN TK ON TL.ID_KARYAWAN = TK.ID_KARYAWAN
                                INNER JOIN TB_DIVISI TD ON TK.ID_DIVISI = TD.ID_DIVISI
                                INNER JOIN TB_JABATAN TJ ON TK.ID_JABATAN = TJ.ID_JABATAN
                                                  
                                INNER JOIN TB_KARYAWAN TKA ON TKA.ID_DIVISI = TK.ID_DIVISI AND 
                                TKA.ID_JABATAN > TK.ID_JABATAN  
                                INNER JOIN TB_JABATAN TJA ON TKA.ID_JABATAN = TJA.ID_JABATAN 
                                WHERE TL.status_lembur = 'Waiting for approve'
                                AND TKA.NIK = ?
                         ORDER BY TL.ID_SPL
                         
                         """;
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, no);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("SPL_NO"),
                    rs.getString("NIK"),
                    rs.getString("nama_karyawan"),
                    rs.getDate("tanggal"),
                    rs.getString("jam_mulai"),
                    rs.getString("jam_selesai"),
                    rs.getString("status_lembur"),
                    rs.getString("nama_atasan")
                });
            }

            tbl.setModel(model);

        } catch (Exception e) {

        }
    }
    
    private void loadData() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("NO SPL");
        model.addColumn("NIK");
        model.addColumn("NAMA KARYAWAN");
        model.addColumn("TANGGAL");
        model.addColumn("JAM MULAI");
        model.addColumn("JAM SELESAI");
        model.addColumn("STATUS");
        model.addColumn("ATASAN");

        try {
            String sql = """
                         SELECT
                                TL.SPL_NO,
                                TK.NIK,
                                TK.NAMA_KARYAWAN,
                                TL.TANGGAL,
                                TL.JAM_MULAI,
                                TL.JAM_SELESAI,
                                TL.STATUS_LEMBUR,
                                TKA.NAMA_KARYAWAN AS NAMA_ATASAN FROM TB_LEMBUR TL 
                                INNER JOIN TB_KARYAWAN TK ON TL.ID_KARYAWAN = TK.ID_KARYAWAN
                                INNER JOIN TB_DIVISI TD ON TK.ID_DIVISI = TD.ID_DIVISI
                                INNER JOIN TB_JABATAN TJ ON TK.ID_JABATAN = TJ.ID_JABATAN
                                                  
                                INNER JOIN TB_KARYAWAN TKA ON TKA.ID_DIVISI = TK.ID_DIVISI AND 
                                TKA.ID_JABATAN > TK.ID_JABATAN  
                                INNER JOIN TB_JABATAN TJA ON TKA.ID_JABATAN = TJA.ID_JABATAN 
                                WHERE TL.status_lembur = 'Waiting for approve'
                                
                         ORDER BY TL.ID_SPL
                         
                         """;
            PreparedStatement ps = conn.prepareStatement(sql);
//            ps.setString(1, nik);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("SPL_NO"),
                    rs.getString("NIK"),
                    rs.getString("nama_karyawan"),
                    rs.getDate("tanggal"),
                    rs.getString("jam_mulai"),
                    rs.getString("jam_selesai"),
                    rs.getString("status_lembur"),
                    rs.getString("nama_atasan")
                });
            }

            tbl.setModel(model);

        } catch (Exception e) {

        }
    }

    private void loadTbleClick() {
        try {
            String sql = """
                            SELECT
                                TL.SPL_NO,
                                TK.NIK,
                                TK.NAMA_KARYAWAN,
                                TL.TANGGAL,
                                TL.JAM_MULAI,
                                TL.JAM_SELESAI,
                                TL.KETERANGAN,
                                TL.STATUS_LEMBUR,
                                TKA.NAMA_KARYAWAN AS NAMA_ATASAN FROM TB_LEMBUR TL 
                                INNER JOIN TB_KARYAWAN TK ON TL.ID_KARYAWAN = TK.ID_KARYAWAN
                                INNER JOIN TB_DIVISI TD ON TK.ID_DIVISI = TD.ID_DIVISI
                                INNER JOIN TB_JABATAN TJ ON TK.ID_JABATAN = TJ.ID_JABATAN
                                                                                                       
                                INNER JOIN TB_KARYAWAN TKA ON TKA.ID_DIVISI = TK.ID_DIVISI AND 
                                TKA.ID_JABATAN > TK.ID_JABATAN  
                                INNER JOIN TB_JABATAN TJA ON TKA.ID_JABATAN = TJA.ID_JABATAN 
                                WHERE TK.NIK = ?
                                """;

            int row = tbl.getSelectedRow();
            String clickTable = (tbl.getModel().getValueAt(row, 1).toString());

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, clickTable);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                spl.setText(rs.getString("spl_no"));
                spl.setEnabled(false);

                namaKar.setText(rs.getString("nama_karyawan"));
                tgl.setDate(rs.getDate("TANGGAL"));
                mulai.setText(rs.getString("jam_mulai"));
                selesai.setText(rs.getString("jam_selesai"));
                ket.setText(rs.getString("keterangan"));
            }

        } catch (Exception e) {

        }
    }

    private void buttonGroup() {
        s.addActionListener(e -> {
            if (s.isSelected()) {
                td.setSelected(false);
                r.setSelected(false);
            }
        });

        td.addActionListener(e -> {
            if (td.isSelected()) {
                s.setSelected(false);
                r.setSelected(false);
            }
        });
        r.addActionListener(e -> {
            if (r.isSelected()) {
                td.setSelected(false);
                s.setSelected(false);
            }
        });
    }
    private void mulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mulaiActionPerformed

    private void splActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_splActionPerformed

    }//GEN-LAST:event_splActionPerformed


    private void namaKarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaKarActionPerformed

    }//GEN-LAST:event_namaKarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sActionPerformed

    private void tdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        loadTbleClick();
    }//GEN-LAST:event_tblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JTextField desc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea ket;
    private javax.swing.JTextField mulai;
    private javax.swing.JTextField namaKar;
    private javax.swing.JTextField nikTxt1;
    private javax.swing.JTextField persetujuan;
    private javax.swing.JCheckBox r;
    private javax.swing.JCheckBox s;
    private javax.swing.JTextField selesai;
    private javax.swing.JTextField spl;
    private javax.swing.JTable tbl;
    private javax.swing.JCheckBox td;
    private com.toedter.calendar.JDateChooser tgl;
    // End of variables declaration//GEN-END:variables
}
