package Beranda;
        import Connect.ConnectDB;
        import Loginreg.*;
        import com.mysql.jdbc.Connection;
        import com.mysql.jdbc.Statement;
        import constant.Constants;
import java.io.File;
        import java.sql.PreparedStatement;
        import java.sql.ResultSet;
import java.util.HashMap;
        import javax.swing.JOptionPane;
        import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author ASUS
 */
public class cuti extends javax.swing.JPanel {
 private Connection conn = (Connection) new ConnectDB().connect();
                  public cuti(String nomor, String nama) {
                  initComponents();
                  tampilData();
                    akhir.addPropertyChangeListener("date", evt -> {
                        if (awal.getDate() != null && akhir.getDate() != null) {
                            long beda = akhir.getDate().getTime() - awal.getDate().getTime();
                            long jumlahHari = (beda / (1000 * 60 * 60 * 24)) + 1; // +1 agar inklusif
                            if (jumlahHari >= 0) {
                                lama.setText(String.valueOf(jumlahHari));
                            } else {
                                lama.setText("");
                                JOptionPane.showMessageDialog(this, "Tanggal akhir tidak boleh sebelum tanggal awal!");
                            }
                        }
                    });

                   nik.setText(nomor);
                   name.setText(nama);

                    nik.setEnabled(false);
                    name.setEnabled(false);
                    persetujuan.setEnabled(false);
                    ket.setEnabled(false);
                    lama.setEnabled(false);
                    awal.setDate(new java.util.Date());
            }
                
            void kosong(){
                    awal.setDate(new java.util.Date());
                    akhir.setDate(new java.util.Date());
                    lama.setText("");
                    alasan.setText("");
                    persetujuan.setText("");
                    ket.setText("");
                }
                

            private void tampilData() {
    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Nama Karyawan");
    model.addColumn("Tgl Awal");
    model.addColumn("Tgl Akhir");
    model.addColumn("Alasan");
    model.addColumn("Lama");
    model.addColumn("Status");
    model.addColumn("Persetujuan"); // <--- Tambahan

    try {
        String sql = """
            SELECT 
                c.id_cuti,
                k.nama_karyawan,
                c.tgl_awal,
                c.tgl_akhir,
                c.alasan,
                c.lama_cuti,
                c.status_cuti,
                c.approval_spv_desc1
            FROM tb_cuti c
            JOIN tb_karyawan k ON c.id_karyawan = k.id_karyawan
            WHERE c.record_flag = 'N' AND c.id_karyawan = ?
        """;

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, loginn.idKaryawanLogin); // ambil ID karyawan yang login
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_cuti"),
                rs.getString("nama_karyawan"),
                rs.getDate("tgl_awal"),
                rs.getDate("tgl_akhir"),
                rs.getString("alasan"),
                rs.getInt("lama_cuti"),
                rs.getString("status_cuti"),
                rs.getString("approval_spv_desc1") != null ? rs.getString("approval_spv_desc1") : "-" // jika NULL, tampil "-"
            });
        }

        tbl.setModel(model);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal tampil data: " + e.getMessage());
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        nik = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        awal = new com.toedter.calendar.JDateChooser();
        akhir = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        lama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        persetujuan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ket = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        alasan = new javax.swing.JTextArea();
        Cetak = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pengajuan Cuti");

        tbl.setBackground(new java.awt.Color(255, 255, 255));
        tbl.setForeground(new java.awt.Color(0, 0, 0));
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        nik.setBackground(new java.awt.Color(255, 253, 246));
        nik.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        nik.setForeground(new java.awt.Color(30, 30, 30));
        nik.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 30, 30));
        jLabel4.setText("Tanggal Mulai");

        name.setBackground(new java.awt.Color(255, 253, 246));
        name.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(30, 30, 30));
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 30, 30));
        jLabel5.setText("Nama Karyawan");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("Nomor Induk Karyawan");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(30, 30, 30));
        jLabel11.setText("Tanggal Akhir");

        simpan.setBackground(new java.awt.Color(0, 0, 102));
        simpan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        simpan.setForeground(new java.awt.Color(255, 255, 255));
        simpan.setText("Simpan");
        simpan.setBorderPainted(false);
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 30, 30));
        jLabel6.setText("Lama Cuti");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 30, 30));
        jLabel7.setText("Alasan Cuti");

        clear.setBackground(new java.awt.Color(0, 0, 102));
        clear.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.setBorderPainted(false);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        lama.setBackground(new java.awt.Color(255, 253, 246));
        lama.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lama.setForeground(new java.awt.Color(30, 30, 30));
        lama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(30, 30, 30));
        jLabel10.setText("Persetujuan");

        persetujuan.setBackground(new java.awt.Color(255, 253, 246));
        persetujuan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        persetujuan.setForeground(new java.awt.Color(30, 30, 30));
        persetujuan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 30, 30));
        jLabel9.setText("Keterangan");

        ket.setBackground(new java.awt.Color(255, 253, 246));
        ket.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        ket.setForeground(new java.awt.Color(30, 30, 30));
        ket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        alasan.setBackground(new java.awt.Color(255, 255, 255));
        alasan.setColumns(20);
        alasan.setForeground(new java.awt.Color(0, 0, 0));
        alasan.setRows(5);
        jScrollPane2.setViewportView(alasan);

        Cetak.setBackground(new java.awt.Color(0, 0, 102));
        Cetak.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Cetak.setForeground(new java.awt.Color(255, 255, 255));
        Cetak.setText("Cetak");
        Cetak.setBorderPainted(false);
        Cetak.setPreferredSize(new java.awt.Dimension(0, 50));
        Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(647, 647, 647))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(persetujuan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ket)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(awal, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nik, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name)
                                    .addComponent(akhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nik, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(awal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(akhir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(persetujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        String nikInput = nik.getText();
        java.util.Date tglAwal = awal.getDate();
        java.util.Date tglAkhir = akhir.getDate();
        String alasanCuti = alasan.getText();

        // Validasi input kosong
        if (nikInput.isEmpty() || tglAwal == null || tglAkhir == null || alasanCuti.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap lengkapi semua isian!");
            return;
        }

        // Validasi tanggal
        long beda = tglAkhir.getTime() - tglAwal.getTime();
        long jumlahHari = (beda / (1000 * 60 * 60 * 24)) + 1;
        if (jumlahHari <= 0) {
            JOptionPane.showMessageDialog(this, "Tanggal akhir harus setelah tanggal awal.");
            return;
        }

        // Validasi maksimal cuti 12 hari
        if (jumlahHari > 12) {
            JOptionPane.showMessageDialog(this, "Durasi cuti maksimal 12 hari.");
            return;
        }

        try {
            // Ambil ID dan jabatan dari NIK
            String sqlKaryawan = """
                SELECT k.id_karyawan, j.nama_jabatan
                FROM tb_karyawan k
                JOIN tb_jabatan j ON k.id_jabatan = j.id_jabatan
                WHERE k.nik = ?
            """;
            PreparedStatement ps1 = conn.prepareStatement(sqlKaryawan);
            ps1.setString(1, nikInput);
            ResultSet rs1 = ps1.executeQuery();

            if (!rs1.next()) {
                JOptionPane.showMessageDialog(this, "Data karyawan tidak ditemukan.");
                return;
            }

            int idKaryawan = rs1.getInt("id_karyawan");
            String namaJabatan = rs1.getString("nama_jabatan");

            // Validasi cuti overlap
            String sqlCheckOverlap = """
                SELECT COUNT(*) FROM tb_cuti
                WHERE id_karyawan = ?
                  AND record_flag = 'N'
                  AND (
                      (? BETWEEN tgl_awal AND tgl_akhir) OR
                      (? BETWEEN tgl_awal AND tgl_akhir) OR
                      (tgl_awal BETWEEN ? AND ?) OR
                      (tgl_akhir BETWEEN ? AND ?)
                  )
            """;
            PreparedStatement psCheck = conn.prepareStatement(sqlCheckOverlap);
            psCheck.setInt(1, idKaryawan);
            psCheck.setDate(2, new java.sql.Date(tglAwal.getTime()));
            psCheck.setDate(3, new java.sql.Date(tglAkhir.getTime()));
            psCheck.setDate(4, new java.sql.Date(tglAwal.getTime()));
            psCheck.setDate(5, new java.sql.Date(tglAkhir.getTime()));
            psCheck.setDate(6, new java.sql.Date(tglAwal.getTime()));
            psCheck.setDate(7, new java.sql.Date(tglAkhir.getTime()));
            ResultSet rsCheck = psCheck.executeQuery();

            if (rsCheck.next() && rsCheck.getInt(1) > 0) {
                JOptionPane.showMessageDialog(this, "Tanggal cuti bentrok dengan pengajuan sebelumnya.");
                return;
            }

            // Simpan data ke tb_cuti
            String sqlInsert = """
                INSERT INTO tb_cuti 
                (id_karyawan, tgl_awal, tgl_akhir, alasan, lama_cuti, create_by, create_at, record_flag, approval_spv_by1, status_cuti)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """;
            PreparedStatement ps2 = conn.prepareStatement(sqlInsert);
            ps2.setInt(1, idKaryawan);
            ps2.setDate(2, new java.sql.Date(tglAwal.getTime()));
            ps2.setDate(3, new java.sql.Date(tglAkhir.getTime()));
            ps2.setString(4, alasanCuti);
            ps2.setInt(5, (int) jumlahHari);
            ps2.setString(6, namaJabatan); // create_by
            ps2.setDate(7, new java.sql.Date(System.currentTimeMillis())); // create_at
            ps2.setString(8, "N"); // record_flag
            ps2.setString(9, null); // approval_spv_by1 (belum diset)
            ps2.setString(10, "Waiting for approve"); // status_cuti ✅ WAJIB

            ps2.executeUpdate();

            JOptionPane.showMessageDialog(this, "Pengajuan cuti berhasil disimpan.");
            kosong();
            tampilData();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data cuti: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       kosong();
    }//GEN-LAST:event_clearActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        int row = tbl.getSelectedRow();
        if (row >= 0) {
            // Ambil data dari kolom tabel
            String tglAwal = tbl.getValueAt(row, 2).toString();
            String tglAkhir = tbl.getValueAt(row, 3).toString();
            String alasanCuti = tbl.getValueAt(row, 4).toString();
            String statusCuti = tbl.getValueAt(row, 6).toString();         // kolom ke-6: Status
            String approvalKet = tbl.getValueAt(row, 7).toString();        // kolom ke-7: Persetujuan

            try {
                // Konversi tanggal dari String ke java.util.Date
                java.util.Date dateAwal = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tglAwal);
                java.util.Date dateAkhir = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tglAkhir);

                // Isi data ke komponen form
                awal.setDate(dateAwal);
                akhir.setDate(dateAkhir);
                alasan.setText(alasanCuti);
                persetujuan.setText(statusCuti);         // asumsi ini JTextField atau JLabel
                ket.setText(approvalKet);           // asumsi ini JTextArea atau JTextField

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal mengambil data: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_tblMouseClicked

    private void CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakActionPerformed
        try{
            java.util.Date tglAwal = awal.getDate();
            java.util.Date tglAkhir = akhir.getDate();

            java.sql.Date awal = new java.sql.Date(tglAwal.getTime());
            java.sql.Date akhir = new java.sql.Date(tglAkhir.getTime());

            String reportPath = System.getProperty("user.dir") + File.separator + "src" + File.separator + "laporan" + File.separator + "PengajuanCuti.jasper";

            String nama_karyawan = name.getText();

            HashMap<String, Object> parameters = new HashMap<>();
            parameters.put("nama_karyawan", nama_karyawan); // sesuai di jrxml
            parameters.put("tanggal_mulai", awal);
            parameters.put("tanggal_selesai", akhir);

            JasperPrint print = JasperFillManager.fillReport(reportPath, parameters, conn);
            JasperViewer viewer = new JasperViewer(print, false);
            viewer.setVisible(true);
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_CetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cetak;
    private com.toedter.calendar.JDateChooser akhir;
    private javax.swing.JTextArea alasan;
    private com.toedter.calendar.JDateChooser awal;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField ket;
    private javax.swing.JTextField lama;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField persetujuan;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
