    /*
     * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
     * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
     */
    package Beranda;

    /**
     *
     * @author Dell
     */
    public class Cuti extends javax.swing.JPanel {

        private final Dashboard main;
        private String nomor;
        private String nama;
        public Cuti(Dashboard main, String nik, String name) {
            initComponents();
            this.main = main;
            this.nomor = nik;
            this.nama = name;
            
            nikTxt.setText(nomor);
            namaTxt.setText(nama);
            
            nikTxt.setEnabled(false);
            namaTxt.setEnabled(false);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            nikTxt = new javax.swing.JTextField();
            jButton1 = new javax.swing.JButton();
            jLabel4 = new javax.swing.JLabel();
            namaTxt = new javax.swing.JTextField();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jScrollPane1 = new javax.swing.JScrollPane();
            jTextArea1 = new javax.swing.JTextArea();
            jButton2 = new javax.swing.JButton();
            jTextField3 = new javax.swing.JTextField();
            jDateChooser1 = new com.toedter.calendar.JDateChooser();
            jLabel8 = new javax.swing.JLabel();
            jLabel9 = new javax.swing.JLabel();
            jTextField4 = new javax.swing.JTextField();
            jLabel10 = new javax.swing.JLabel();
            cb1 = new javax.swing.JCheckBox();
            cb2 = new javax.swing.JCheckBox();
            cb3 = new javax.swing.JCheckBox();

            setBackground(new java.awt.Color(255, 253, 246));

            jLabel1.setBackground(new java.awt.Color(255, 253, 246));
            jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(0, 0, 0));
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("Pengajuan Cuti");

            jLabel2.setBackground(new java.awt.Color(255, 253, 246));
            jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(0, 0, 0));
            jLabel2.setText("Nomor Induk Karyawan");

            nikTxt.setBackground(new java.awt.Color(255, 253, 246));
            nikTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
            nikTxt.setForeground(new java.awt.Color(0, 0, 0));
            nikTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            nikTxt.setPreferredSize(new java.awt.Dimension(64, 50));

            jButton1.setBackground(new java.awt.Color(0, 0, 102));
            jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
            jButton1.setForeground(new java.awt.Color(255, 255, 255));
            jButton1.setText("Simpan");
            jButton1.setBorderPainted(false);
            jButton1.setPreferredSize(new java.awt.Dimension(0, 50));
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jLabel4.setBackground(new java.awt.Color(255, 253, 246));
            jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(0, 0, 0));
            jLabel4.setText("Tanggal");

            namaTxt.setBackground(new java.awt.Color(255, 253, 246));
            namaTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
            namaTxt.setForeground(new java.awt.Color(0, 0, 0));
            namaTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            namaTxt.setPreferredSize(new java.awt.Dimension(64, 50));

            jLabel5.setBackground(new java.awt.Color(255, 253, 246));
            jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(0, 0, 0));
            jLabel5.setText("Nama Karyawan");

            jLabel6.setBackground(new java.awt.Color(255, 253, 246));
            jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
            jLabel6.setForeground(new java.awt.Color(0, 0, 0));
            jLabel6.setText("Lama Cuti");

            jLabel7.setBackground(new java.awt.Color(255, 253, 246));
            jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
            jLabel7.setForeground(new java.awt.Color(0, 0, 0));
            jLabel7.setText("Alasan Cuti");

            jTextArea1.setBackground(new java.awt.Color(255, 253, 246));
            jTextArea1.setColumns(20);
            jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
            jTextArea1.setRows(5);
            jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jScrollPane1.setViewportView(jTextArea1);

            jButton2.setBackground(new java.awt.Color(0, 0, 102));
            jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
            jButton2.setForeground(new java.awt.Color(255, 255, 255));
            jButton2.setText("Edit");
            jButton2.setBorderPainted(false);
            jButton2.setPreferredSize(new java.awt.Dimension(0, 50));
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jTextField3.setBackground(new java.awt.Color(255, 253, 246));
            jTextField3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
            jTextField3.setForeground(new java.awt.Color(0, 0, 0));
            jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jTextField3.setPreferredSize(new java.awt.Dimension(64, 50));

            jLabel8.setBackground(new java.awt.Color(255, 253, 246));
            jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
            jLabel8.setForeground(new java.awt.Color(0, 0, 0));
            jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel8.setText("Keterangan");

            jLabel9.setBackground(new java.awt.Color(255, 253, 246));
            jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
            jLabel9.setForeground(new java.awt.Color(0, 0, 0));
            jLabel9.setText("Persetujuan");

            jTextField4.setBackground(new java.awt.Color(255, 253, 246));
            jTextField4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
            jTextField4.setForeground(new java.awt.Color(0, 0, 0));
            jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jTextField4.setPreferredSize(new java.awt.Dimension(64, 50));

            jLabel10.setBackground(new java.awt.Color(255, 253, 246));
            jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
            jLabel10.setForeground(new java.awt.Color(0, 0, 0));
            jLabel10.setText("Keterangan");

            cb1.setBackground(new java.awt.Color(255, 253, 246));
            cb1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
            cb1.setForeground(new java.awt.Color(0, 0, 0));
            cb1.setText("Disetujui");
            cb1.setAutoscrolls(true);
            cb1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cb1ActionPerformed(evt);
                }
            });

            cb2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
            cb2.setForeground(new java.awt.Color(0, 0, 0));
            cb2.setText("Tidak Disetujui");
            cb2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cb2ActionPerformed(evt);
                }
            });

            cb3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
            cb3.setForeground(new java.awt.Color(0, 0, 0));
            cb3.setText("Revisi");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                        .addComponent(namaTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nikTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)))
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cb1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cb2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cb3)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(nikTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(3, 3, 3)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel6)
                    .addGap(5, 5, 5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel7)
                    .addGap(8, 8, 8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel10)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb1)
                        .addComponent(cb2)
                        .addComponent(cb3))
                    .addGap(10, 10, 10)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29))
            );
        }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_jButton1ActionPerformed

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_jButton2ActionPerformed

        private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_cb1ActionPerformed

        private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_cb2ActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JCheckBox cb1;
        private javax.swing.JCheckBox cb2;
        private javax.swing.JCheckBox cb3;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private com.toedter.calendar.JDateChooser jDateChooser1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextArea jTextArea1;
        private javax.swing.JTextField jTextField3;
        private javax.swing.JTextField jTextField4;
        private javax.swing.JTextField namaTxt;
        private javax.swing.JTextField nikTxt;
        // End of variables declaration//GEN-END:variables

        private static class upstream {

            public upstream() {
            }
        }
    }
