package Beranda;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import javax.swing.SwingUtilities;

public class Dashboard extends javax.swing.JFrame {
   private Absensi absen;
   private Lembur lembur;
   private Cuti cuti;
   private Gaji gaji;
   private Resign resign;
   private Tambah tambah;
   private Atur atur;
   private Cari cari;
   private Atur_cuti atcut;
   private Atur_resign ares;
   private String nik;
   private String name;
   
   public void setAbsensi(){
       this.nik = noTxt.getText();
       this.name = namaTxt.getText();
        if(absen == null){
            absen = new Absensi(nik, name);
        }
        jPanel2.removeAll();
        jPanel2.add(absen);
        SwingUtilities.updateComponentTreeUI(jPanel2);
    }
   
   public void setLembur(){
        if(lembur == null){
            lembur = new Lembur(this, name);
        }
        jPanel2.removeAll();
        jPanel2.add(lembur);
        SwingUtilities.updateComponentTreeUI(jPanel2);
    }
   
    public void setResign() {
        this.nik = noTxt.getText();
        this.name = namaTxt.getText();
        if(resign == null){
            resign = new Resign(nik, name);
    }
        jPanel2.removeAll();
        jPanel2.add(resign);
        SwingUtilities.updateComponentTreeUI(jPanel2);
    }
   
   public void setCuti(){
        if(cuti == null){
            cuti = new Cuti(this, nik, name);
        }
        jPanel2.removeAll();
        jPanel2.add(cuti);
        SwingUtilities.updateComponentTreeUI(jPanel2);
    }
   
   public void setGaji(){
        if(gaji == null){
            gaji = new Gaji(this);
        }
        jPanel2.removeAll();
        jPanel2.add(gaji);
        SwingUtilities.updateComponentTreeUI(jPanel2);
    }
   
   public void setTambah(){
        if(tambah == null){
            tambah = new Tambah(this);
        }
        jPanel2.removeAll();
        jPanel2.add(tambah);
        SwingUtilities.updateComponentTreeUI(jPanel2);
    }
   
   public void setAtur(){
        if(atur == null){
            atur = new Atur(this);
        }
        jPanel2.removeAll();
        jPanel2.add(atur);
        SwingUtilities.updateComponentTreeUI(jPanel2);
    }
   
   public void setCari(){
        if(cari == null){
            cari = new Cari(this);
        }
        jPanel2.removeAll();
        jPanel2.add(cari);
        SwingUtilities.updateComponentTreeUI(jPanel2);
    }
   
   public void setAtur_cuti(){
        if(atcut == null){
            atcut = new Atur_cuti(this);
        }
        jPanel2.removeAll();
        jPanel2.add(atcut);
        SwingUtilities.updateComponentTreeUI(jPanel2);
    }
   
   public void setAtur_resign(){
        if(ares == null){
            ares = new Atur_resign(this);
        }
        jPanel2.removeAll();
        jPanel2.add(ares);
        SwingUtilities.updateComponentTreeUI(jPanel2);
    }
   
    public Dashboard(String nomor, String nama) {
        initComponents();
        
        this.nik = nomor;
        this.name = nama;
        
        noTxt.setText(nik);
        namaTxt.setText(name);
        
        noTxt.setEnabled(false);
        namaTxt.setEnabled(false);
        setAbsensi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        babs = new javax.swing.JButton();
        blem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        namaTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        noTxt = new javax.swing.JTextField();
        bres = new javax.swing.JButton();
        bcut = new javax.swing.JButton();
        bgaj = new javax.swing.JButton();
        btam = new javax.swing.JButton();
        bagaj = new javax.swing.JButton();
        batlem = new javax.swing.JButton();
        batres = new javax.swing.JButton();
        batcut = new javax.swing.JButton();
        bcar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1243, 834));

        jPanel1.setBackground(new java.awt.Color(255, 253, 246));

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SelfTracking");
        jLabel1.setOpaque(true);

        babs.setBackground(new java.awt.Color(77, 120, 204));
        babs.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        babs.setForeground(new java.awt.Color(255, 255, 255));
        babs.setText("Absensi");
        babs.setBorderPainted(false);
        babs.setPreferredSize(new java.awt.Dimension(0, 50));
        babs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                babsActionPerformed(evt);
            }
        });

        blem.setBackground(new java.awt.Color(44, 44, 44));
        blem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        blem.setForeground(new java.awt.Color(255, 255, 255));
        blem.setText("Lembur");
        blem.setBorderPainted(false);
        blem.setPreferredSize(new java.awt.Dimension(0, 50));
        blem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blemActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(77, 120, 204));
        jLabel4.setText("Nama");

        namaTxt.setBackground(new java.awt.Color(255, 253, 246));
        namaTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        namaTxt.setForeground(new java.awt.Color(30, 30, 30));
        namaTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(144, 209, 202), 2));
        namaTxt.setPreferredSize(new java.awt.Dimension(0, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(77, 120, 204));
        jLabel5.setText("Nomor Induk Karyawan ");

        noTxt.setBackground(new java.awt.Color(255, 253, 246));
        noTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        noTxt.setForeground(new java.awt.Color(30, 30, 30));
        noTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(144, 209, 202), 2));
        noTxt.setPreferredSize(new java.awt.Dimension(0, 50));

        bres.setBackground(new java.awt.Color(44, 44, 44));
        bres.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        bres.setForeground(new java.awt.Color(255, 255, 255));
        bres.setText("Resign");
        bres.setBorderPainted(false);
        bres.setPreferredSize(new java.awt.Dimension(0, 50));
        bres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresActionPerformed(evt);
            }
        });

        bcut.setBackground(new java.awt.Color(44, 44, 44));
        bcut.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        bcut.setForeground(new java.awt.Color(255, 255, 255));
        bcut.setText("Cuti");
        bcut.setBorderPainted(false);
        bcut.setPreferredSize(new java.awt.Dimension(0, 50));
        bcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcutActionPerformed(evt);
            }
        });

        bgaj.setBackground(new java.awt.Color(44, 44, 44));
        bgaj.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        bgaj.setForeground(new java.awt.Color(255, 255, 255));
        bgaj.setText("Gaji");
        bgaj.setBorderPainted(false);
        bgaj.setPreferredSize(new java.awt.Dimension(0, 50));
        bgaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgajActionPerformed(evt);
            }
        });

        btam.setBackground(new java.awt.Color(44, 44, 44));
        btam.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btam.setForeground(new java.awt.Color(255, 255, 255));
        btam.setText("Tambah Karyawan");
        btam.setBorderPainted(false);
        btam.setPreferredSize(new java.awt.Dimension(0, 50));
        btam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btamActionPerformed(evt);
            }
        });

        bagaj.setBackground(new java.awt.Color(44, 44, 44));
        bagaj.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        bagaj.setForeground(new java.awt.Color(255, 255, 255));
        bagaj.setText("Atur Gaji");
        bagaj.setBorderPainted(false);
        bagaj.setPreferredSize(new java.awt.Dimension(0, 50));
        bagaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagajActionPerformed(evt);
            }
        });

        batlem.setBackground(new java.awt.Color(44, 44, 44));
        batlem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        batlem.setForeground(new java.awt.Color(255, 255, 255));
        batlem.setText("Approval lembur");
        batlem.setBorderPainted(false);
        batlem.setPreferredSize(new java.awt.Dimension(0, 50));
        batlem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batlemActionPerformed(evt);
            }
        });

        batres.setBackground(new java.awt.Color(44, 44, 44));
        batres.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        batres.setForeground(new java.awt.Color(255, 255, 255));
        batres.setText("Approval Resign");
        batres.setBorderPainted(false);
        batres.setPreferredSize(new java.awt.Dimension(0, 50));
        batres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batresActionPerformed(evt);
            }
        });

        batcut.setBackground(new java.awt.Color(44, 44, 44));
        batcut.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        batcut.setForeground(new java.awt.Color(255, 255, 255));
        batcut.setText("Approval Cuti");
        batcut.setBorderPainted(false);
        batcut.setPreferredSize(new java.awt.Dimension(0, 50));
        batcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batcutActionPerformed(evt);
            }
        });

        bcar.setBackground(new java.awt.Color(44, 44, 44));
        bcar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        bcar.setForeground(new java.awt.Color(255, 255, 255));
        bcar.setText("Cari Absen");
        bcar.setBorderPainted(false);
        bcar.setPreferredSize(new java.awt.Dimension(0, 50));
        bcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(noTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(babs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bcut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bgaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bagaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(batlem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(batres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(batcut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bcar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(babs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bcut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bgaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bagaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bcar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(batlem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(batcut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(batres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        jPanel2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void babsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_babsActionPerformed
        // TODO add your handling code here:
        babs.setBackground(new Color(77,120,204));
        blem.setBackground(new Color(44,44,44));
        bres.setBackground(new Color(44,44,44));
        bcut.setBackground(new Color(44,44,44));
        bgaj.setBackground(new Color(44,44,44));
        bagaj.setBackground(new Color(44,44,44));
        btam.setBackground(new Color(44,44,44));
        bcar.setBackground(new Color(44,44,44));
        setAbsensi();
    }//GEN-LAST:event_babsActionPerformed

    private void blemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blemActionPerformed
        // TODO add your handling code here:
        blem.setBackground(new Color(77,120,204));
        babs.setBackground(new Color(44,44,44));
        bres.setBackground(new Color(44,44,44));
        bcut.setBackground(new Color(44,44,44));
        bgaj.setBackground(new Color(44,44,44));
        bagaj.setBackground(new Color(44,44,44));
        btam.setBackground(new Color(44,44,44));
        bcar.setBackground(new Color(44,44,44));
        setLembur();
    }//GEN-LAST:event_blemActionPerformed

    private void bresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresActionPerformed
        // TODO add your handling code here:
        bres.setBackground(new Color(77,120,204));
        babs.setBackground(new Color(44,44,44));
        blem.setBackground(new Color(44,44,44));
        bcut.setBackground(new Color(44,44,44));
        bgaj.setBackground(new Color(44,44,44));
        bgaj.setBackground(new Color(44,44,44));
        btam.setBackground(new Color(44,44,44));
        bcar.setBackground(new Color(44,44,44));
        setResign();
    }//GEN-LAST:event_bresActionPerformed

    private void bcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcutActionPerformed
        // TODO add your handling code here:
        bcut.setBackground(new Color(77,120,204));
        babs.setBackground(new Color(44,44,44));
        blem.setBackground(new Color(44,44,44));
        bres.setBackground(new Color(44,44,44));
        bgaj.setBackground(new Color(44,44,44));
        bagaj.setBackground(new Color(44,44,44));
        btam.setBackground(new Color(44,44,44));
        bcar.setBackground(new Color(44,44,44));
        setCuti();
    }//GEN-LAST:event_bcutActionPerformed

    private void bgajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgajActionPerformed
        // TODO add your handling code here:
        bgaj.setBackground(new Color(77,120,204));
        babs.setBackground(new Color(44,44,44));
        blem.setBackground(new Color(44,44,44));
        bres.setBackground(new Color(44,44,44));
        bcut.setBackground(new Color(44,44,44));
        bagaj.setBackground(new Color(44,44,44));
        btam.setBackground(new Color(44,44,44));
        bcar.setBackground(new Color(44,44,44));
        setGaji();
    }//GEN-LAST:event_bgajActionPerformed

    private void btamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btamActionPerformed
        // TODO add your handling code here:
        btam.setBackground(new Color(77,120,204));
        babs.setBackground(new Color(44,44,44));
        blem.setBackground(new Color(44,44,44));
        bres.setBackground(new Color(44,44,44));
        bcut.setBackground(new Color(44,44,44));
        bagaj.setBackground(new Color(44,44,44));
        bgaj.setBackground(new Color(44,44,44));
        bcar.setBackground(new Color(44,44,44));
        setTambah();
    }//GEN-LAST:event_btamActionPerformed

    private void bagajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagajActionPerformed
        // TODO add your handling code here:
        bagaj.setBackground(new Color(77,120,204));
        babs.setBackground(new Color(44,44,44));
        blem.setBackground(new Color(44,44,44));
        bres.setBackground(new Color(44,44,44));
        bcut.setBackground(new Color(44,44,44));
        bgaj.setBackground(new Color(44,44,44));
        btam.setBackground(new Color(44,44,44));
        bcar.setBackground(new Color(44,44,44));
        setAtur();
    }//GEN-LAST:event_bagajActionPerformed

    private void batlemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batlemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batlemActionPerformed

    private void batresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batresActionPerformed
        // TODO add your handling code here:
        batres.setBackground(new Color(77,120,204));
        babs.setBackground(new Color(44,44,44));
        blem.setBackground(new Color(44,44,44));
        bres.setBackground(new Color(44,44,44));
        bcut.setBackground(new Color(44,44,44));
        bgaj.setBackground(new Color(44,44,44));
        btam.setBackground(new Color(44,44,44));
        bagaj.setBackground(new Color(44,44,44));
        batcut.setBackground(new Color(44,44,44));
        bcar.setBackground(new Color(44,44,44));
        setAtur_resign();
    }//GEN-LAST:event_batresActionPerformed

    private void batcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batcutActionPerformed
        // TODO add your handling code here:
        batcut.setBackground(new Color(77,120,204));
        babs.setBackground(new Color(44,44,44));
        blem.setBackground(new Color(44,44,44));
        bres.setBackground(new Color(44,44,44));
        bcut.setBackground(new Color(44,44,44));
        bgaj.setBackground(new Color(44,44,44));
        btam.setBackground(new Color(44,44,44));
        bagaj.setBackground(new Color(44,44,44));
        batres.setBackground(new Color(44,44,44));
        bcar.setBackground(new Color(44,44,44));
        setAtur_cuti();
    }//GEN-LAST:event_batcutActionPerformed

    private void bcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcarActionPerformed
        // TODO add your handling code here:
        bcar.setBackground(new Color(77,120,204));
        babs.setBackground(new Color(44,44,44));
        blem.setBackground(new Color(44,44,44));
        bres.setBackground(new Color(44,44,44));
        bcut.setBackground(new Color(44,44,44));
        bgaj.setBackground(new Color(44,44,44));
        btam.setBackground(new Color(44,44,44));
        bagaj.setBackground(new Color(44,44,44));
        setCari();
    }//GEN-LAST:event_bcarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarkLaf.setup();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton babs;
    private javax.swing.JButton bagaj;
    private javax.swing.JButton batcut;
    private javax.swing.JButton batlem;
    private javax.swing.JButton batres;
    private javax.swing.JButton bcar;
    private javax.swing.JButton bcut;
    private javax.swing.JButton bgaj;
    private javax.swing.JButton blem;
    private javax.swing.JButton bres;
    private javax.swing.JButton btam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JTextField noTxt;
    // End of variables declaration//GEN-END:variables
}
