/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Beranda;
import Connect.ConnectDB;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Date;

import constant.Constants;
import java.io.File;
import java.util.HashMap;
import java.util.Random;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import util.ValidateUtil;

/**
 *
 * @author Dell
 */
public class Laporan extends javax.swing.JPanel {

    private Connection conn = (Connection) new ConnectDB().connect();
    
    private final Dashboard main;
    public Laporan(Dashboard main) {
        initComponents();
        this.main = main;

        isiComboBoxLayanan();
        isiComboBoxDivisi();
        handleComboChange(); // langsung atur tampilan awal

        cbLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleComboChange();
            }
        });
    }

    private void isiComboBoxLayanan() {
        cbLayanan.addItem("Pilih");
        cbLayanan.addItem("Absen");
        cbLayanan.addItem("Lembur");
        cbLayanan.addItem("Cuti");
        cbLayanan.addItem("Gaji");
        cbLayanan.addItem("Slip Gaji");
    }

    private void isiComboBoxDivisi() {
        cbDivisi.addItem("Pilih");
        cbDivisi.addItem("IT");
        cbDivisi.addItem("QA");
        cbDivisi.addItem("ADMINISTRASI");
        cbDivisi.addItem("KEUANGAN");
        cbDivisi.addItem("GUDANG");
    }

    private void handleComboChange() {
        String selected = cbLayanan.getSelectedItem().toString();

        boolean showNamaNik = selected.equalsIgnoreCase("Slip Gaji");
        boolean showDivisi = selected.equalsIgnoreCase("Absen") || selected.equalsIgnoreCase("Gaji");
        boolean showTanggal = !selected.equalsIgnoreCase("Pilih");

        // Field Nama & NIK
        jLabel8.setVisible(showNamaNik);        // Label Nama
        name.setVisible(showNamaNik);    // Field Nama

        // Divisi
        labelDivisi.setVisible(showDivisi);        // Label Divisi
        cbDivisi.setVisible(showDivisi);        // ComboBox Divisi

        // Tanggal Awal & Akhir
        jLabel6.setVisible(showTanggal);        // Label Tgl Awal
        fr.setVisible(showTanggal);             // DateChooser Awal
        jLabel7.setVisible(showTanggal);        // Label Tgl Akhir
        fr2.setVisible(showTanggal);            // DateChooser Akhir
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fr = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        fr2 = new com.toedter.calendar.JDateChooser();
        cbLayanan = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        cbDivisi = new javax.swing.JComboBox<>();
        labelDivisi = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 253, 246));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Laporan");

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cetak");
        jButton1.setBorderPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(0, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 30, 30));
        jLabel9.setText("Cari Layanan");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 30, 30));
        jLabel6.setText("Tanggal Awal");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 30, 30));
        jLabel7.setText("Tanggal Akhir");

        cbLayanan.setBackground(new java.awt.Color(255, 253, 246));
        cbLayanan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        cbLayanan.setForeground(new java.awt.Color(30, 30, 30));
        cbLayanan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(30, 30, 30));
        jLabel8.setText("Nama Karyawan");

        name.setBackground(new java.awt.Color(255, 253, 246));
        name.setForeground(new java.awt.Color(30, 30, 30));
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cbDivisi.setBackground(new java.awt.Color(255, 253, 246));
        cbDivisi.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        cbDivisi.setForeground(new java.awt.Color(30, 30, 30));
        cbDivisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbDivisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDivisiActionPerformed(evt);
            }
        });

        labelDivisi.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        labelDivisi.setForeground(new java.awt.Color(30, 30, 30));
        labelDivisi.setText("Divisi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 158, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 159, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbLayanan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name)
                    .addComponent(cbDivisi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fr2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDivisi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDivisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDivisi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fr, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(5, 5, 5)
                .addComponent(fr2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        String layanan = cbLayanan.getSelectedItem().toString();

        if (layanan.equalsIgnoreCase("Pilih")) {
            JOptionPane.showMessageDialog(this, "Silakan pilih jenis laporan terlebih dahulu.");
            return;
        }

        // Konversi tanggal
        java.util.Date tglAwalUtil = fr.getDate();
        java.util.Date tglAkhirUtil = fr2.getDate();

        if (tglAwalUtil == null || tglAkhirUtil == null) {
            JOptionPane.showMessageDialog(this, "Tanggal awal dan akhir tidak boleh kosong.");
            return;
        }

        java.sql.Date tanggalAwal = new java.sql.Date(tglAwalUtil.getTime());
        java.sql.Date tanggalAkhir = new java.sql.Date(tglAkhirUtil.getTime());

        // Tentukan path file Jasper
        String basePath = "src/laporan/";
        String fileJasper = "";
        switch (layanan.toLowerCase()) {
            case "absen":
                fileJasper = basePath + "LaporanAbsen.jasper";
                break;
            case "lembur":
                fileJasper = basePath + "LaporanLembur.jasper";
                break;
            case "cuti":
                fileJasper = basePath + "LaporanCuti.jasper";
                break;
            case "gaji":
                fileJasper = basePath + "LaporanGaji.jasper";
                break;
            case "slip gaji":
                fileJasper = basePath + "SlipGaji.jasper";
                break;
            default:
                JOptionPane.showMessageDialog(this, "Jenis laporan tidak dikenali.");
                return;
        }

        // Buat parameter
        HashMap<String, Object> parameters = new HashMap<>();
        parameters.put("tanggalAwal", tanggalAwal);
        parameters.put("tanggalAkhir", tanggalAkhir);

        // Parameter khusus Slip Gaji
        if (layanan.equalsIgnoreCase("Slip Gaji")) {
            parameters.put("nama_karyawan", name.getText());
        }

        // Parameter khusus Absen atau Gaji
        if (layanan.equalsIgnoreCase("Absen") || layanan.equalsIgnoreCase("Gaji")) {
            parameters.put("divisi", cbDivisi.getSelectedItem().toString());
        }

        // Jalankan laporan
        JasperPrint print = JasperFillManager.fillReport(fileJasper, parameters, conn);
        JasperViewer viewer = new JasperViewer(print, false);
        viewer.setVisible(true);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal mencetak laporan:\n" + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbDivisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDivisiActionPerformed
        
    }//GEN-LAST:event_cbDivisiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbDivisi;
    private javax.swing.JComboBox<String> cbLayanan;
    private com.toedter.calendar.JDateChooser fr;
    private com.toedter.calendar.JDateChooser fr2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelDivisi;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
