/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Beranda;

import Connect.ConnectDB;
import Loginreg.*;
import com.mysql.jdbc.Connection;
import constant.Constants;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Lembur extends javax.swing.JPanel {

    private Connection conn = (Connection) new ConnectDB().connect();
    private final Dashboard main;

    private String nama;
    private String nik;

    public Lembur(Dashboard main, String nik, String name) {
        initComponents();
        this.main = main;
        this.nama = name;
        this.nik = nik;

        namaKar.setText(nama);
        namaKar.setEnabled(false);
        spl.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spl = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        namaKar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ket = new javax.swing.JTextArea();
        edit = new javax.swing.JButton();
        mulai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        selesai = new javax.swing.JTextField();
        tgl = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 253, 246));

        jLabel1.setBackground(new java.awt.Color(30, 30, 30));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pengisian Lembur");

        jLabel2.setBackground(new java.awt.Color(30, 30, 30));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("No Spl");

        spl.setBackground(new java.awt.Color(255, 253, 246));
        spl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        spl.setForeground(new java.awt.Color(30, 30, 30));
        spl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spl.setPreferredSize(new java.awt.Dimension(64, 50));
        spl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splActionPerformed(evt);
            }
        });

        save.setBackground(new java.awt.Color(0, 0, 102));
        save.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Simpan");
        save.setBorderPainted(false);
        save.setPreferredSize(new java.awt.Dimension(0, 50));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(30, 30, 30));
        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 30, 30));
        jLabel4.setText("Tanggal");

        namaKar.setEditable(false);
        namaKar.setBackground(new java.awt.Color(255, 253, 246));
        namaKar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        namaKar.setForeground(new java.awt.Color(30, 30, 30));
        namaKar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        namaKar.setPreferredSize(new java.awt.Dimension(64, 50));
        namaKar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaKarActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(30, 30, 30));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 30, 30));
        jLabel5.setText("Nama Karyawan");

        jLabel6.setBackground(new java.awt.Color(30, 30, 30));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 30, 30));
        jLabel6.setText("Jam Mulai");

        jLabel7.setBackground(new java.awt.Color(30, 30, 30));
        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 30, 30));
        jLabel7.setText("Keterangan");

        ket.setBackground(new java.awt.Color(255, 253, 246));
        ket.setColumns(20);
        ket.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ket.setForeground(new java.awt.Color(30, 30, 30));
        ket.setRows(5);
        ket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(ket);

        edit.setBackground(new java.awt.Color(0, 0, 102));
        edit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("Edit");
        edit.setBorderPainted(false);
        edit.setPreferredSize(new java.awt.Dimension(0, 50));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        mulai.setBackground(new java.awt.Color(255, 253, 246));
        mulai.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        mulai.setForeground(new java.awt.Color(30, 30, 30));
        mulai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mulai.setPreferredSize(new java.awt.Dimension(64, 50));
        mulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(30, 30, 30));
        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(30, 30, 30));
        jLabel8.setText("Jam Selesai");

        selesai.setBackground(new java.awt.Color(255, 253, 246));
        selesai.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        selesai.setForeground(new java.awt.Color(30, 30, 30));
        selesai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        selesai.setPreferredSize(new java.awt.Dimension(64, 50));

        tgl.setBackground(new java.awt.Color(255, 253, 246));
        tgl.setForeground(new java.awt.Color(30, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(spl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaKar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mulai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 294, Short.MAX_VALUE))
                    .addComponent(tgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaKar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mulai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
            String sql = """
                     INSERT INTO TB_LEMBUR 
                     (ID_KARYAWAN,SPL_NO, TANGGAL, JAM_MULAI, JAM_SELESAI,STATUS_LEMBUR, KETERANGAN, CREATE_BY, CREATE_AT, RECORD_FLAG) 
                     VALUES (?,?,?,?,?,?,?,?,?,?)
                     """;
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, cariId(namaKar.getText()));
            ps.setString(2, generateSpl());
            java.util.Date date = tgl.getDate();
            java.sql.Date tanggal = new java.sql.Date(date.getTime());
            ps.setDate(3, tanggal);
            ps.setString(4, mulai.getText());
            ps.setString(5, selesai.getText());
            ps.setString(6, "Waiting for approve");
            ps.setString(7, ket.getText());
            ps.setString(8, "Admin");
            java.util.Date utilDate = new java.util.Date();
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            ps.setDate(9, sqlDate);
            ps.setString(10, Constants.RECORD_FLAG_N);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Simpan");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak ke Simpan " + e.getMessage());
        }
    }//GEN-LAST:event_saveActionPerformed
    private Integer cariId(String namaKaryawan) {
        Integer id = null;
        try {
            String sql = "SELECT ID_KARYAWAN FROM TB_KARYAWAN WHERE NAMA_KARYAWAN = ?";

            System.out.println("Ini Nama Karyawan : " + namaKaryawan);
            System.out.println("Ini SQL : " + sql);

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, namaKaryawan);

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                id = rs.getInt("ID_KARYAWAN");
                System.out.println("Ini ID : " + id);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak terhubung ke TB_Karyawan");
        }
        return id;
    }
    private void mulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mulaiActionPerformed

    private void splActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_splActionPerformed

    }//GEN-LAST:event_splActionPerformed
    private String generateSpl() {
        String val = null;
        SimpleDateFormat sdf = new SimpleDateFormat("MMyy");
        SimpleDateFormat sdf2 = new SimpleDateFormat("yy");
        java.util.Date utilDate = new java.util.Date();

        try {
            int noUrut = 0;
            String spl = "SPL/";

            String sql = """
                       SELECT TB.SPL_NO FROM TB_LEMBUR TB
                       INNER JOIN TB_KARYAWAN TK ON TB.ID_KARYAWAN = TK.ID_KARYAWAN
                       WHERE TK.NIK = ? 
                       ORDER BY TB.SPL_NO DESC
                       """;
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, nik);

            ResultSet rs = ps.executeQuery();
            String nospl = null;

            if (rs.next()) {
                nospl = rs.getString("SPL_NO");

            }

            if (nospl == null) {
                noUrut = 1;
            } else {
                String year = nospl.substring(6, 8);
                
                if (!year.equals(sdf2.format(utilDate))) {
                    noUrut = 1;
                } else {
                    noUrut = Integer.parseInt(nospl.substring(15, 18));
                    noUrut++;
                }
            }

            val = spl + sdf.format(utilDate) + "/" + nik + "/" + String.format("%03d", noUrut);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak terhubung ke " + e.getMessage());
        }
        return val;
    }
    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void namaKarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaKarActionPerformed

    }//GEN-LAST:event_namaKarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ket;
    private javax.swing.JTextField mulai;
    private javax.swing.JTextField namaKar;
    private javax.swing.JButton save;
    private javax.swing.JTextField selesai;
    private javax.swing.JTextField spl;
    private com.toedter.calendar.JDateChooser tgl;
    // End of variables declaration//GEN-END:variables
}
